id = "devtime"
name = "devtime"
description = "Local-first coding time tracking."
version = "0.0.5"
schema_version = 1
authors = ["Arnaud Huret <arnaud3488@gmail.com>"]
repository = "https://github.com/arnaudhrt/devtime-zed"

[language_servers.devtime]
name = "devtime"
languages = [
    "ActionScript",
    "Ada",
    "Agda",
    "Aiken",
    "Amber",
    "Ansible",
    "AsciiDoc",
    "Assembly",
    "Astro",
    "AWK",
    "Shell Script",
    "Beancount",
    "Bend",
    "Blade",
    "Blueprint",
    "Brainfuck",
    "C",
    "C#",
    "C++",
    "C3",
    "Caddyfile",
    "Cadence",
    "Cairo",
    "Cap'n Proto",
    "Cedar",
    "Clojure",
    "COBOL",
    "CoffeeScript",
    "Crystal",
    "CSS",
    "CSV",
    "CUE",
    "Cython",
    "D",
    "D2",
    "Dafny",
    "Dart",
    "DBML",
    "Diff",
    "Docker Compose",
    "Dockerfile",
    "Earthfile",
    "EJS",
    "Elisp",
    "Elixir",
    "Elm",
    "env",
    "ERB",
    "Erlang",
    "Fish",
    "FlatBuffers",
    "Fortran",
    "FSharp",
    "GDScript",
    "Gemini",
    "Gherkin",
    "Git Attributes",
    "Git Commit",
    "Git Config",
    "Git Ignore",
    "Git Rebase",
    "Gleam",
    "GLSL",
    "Go",
    "Go Mod",
    "Go Sum",
    "Go Work",
    "Godot Resource",
    "GraphQL",
    "Groovy",
    "Haml",
    "Handlebars",
    "Hare",
    "Haskell",
    "Haxe",
    "HCL",
    "HEEX",
    "Helm",
    "HLSL",
    "HTML",
    "http",
    "Hurl",
    "Idris2",
    "ini",
    "Janet",
    "Java",
    "JavaScript",
    "Jinja2",
    "JSON",
    "JSONC",
    "Jsonnet",
    "JSDoc",
    "JSX",
    "Julia",
    "Just",
    "Kdl",
    "Kotlin",
    "LaTeX",
    "BibTeX",
    "Ledger",
    "LESS",
    "Liquid",
    "LOG",
    "Lua",
    "Luau",
    "Make",
    "Markdown",
    "Markdown-Inline",
    "MATLAB",
    "Move",
    "CMake",
    "Nginx",
    "Nickel",
    "Nim",
    "Nix",
    "Noir",
    "Nu",
    "Dune",
    "Objective-C",
    "OCaml",
    "OCaml Interface",
    "Odin",
    "OpenSCAD",
    "OpenTofu",
    "Org",
    "Pact",
    "Perl",
    "Pest",
    "PHP",
    "PHPDoc",
    "Pkl",
    "PlantUML",
    "PowerShell",
    "Prisma",
    "Prolog",
    "Properties",
    "Proto",
    "Pug",
    "PureScript",
    "Python",
    "QML",
    "R",
    "Racket",
    "RBS",
    "Regex",
    "rego",
    "ReScript",
    "reST",
    "Roc",
    "RON",
    "Ruby",
    "Rust",
    "SageMath",
    "Scala",
    "Scheme",
    "SCSS",
    "Shell Script",
    "Slim",
    "Smithy",
    "Snakemake",
    "Solidity",
    "SQL",
    "SSH Config",
    "Stan",
    "Standard ML",
    "Starlark",
    "Svelte",
    "Swift",
    "Templ",
    "Tera",
    "Terraform",
    "Terraform Vars",
    "TOML",
    "Tree-sitter Query",
    "TSX",
    "Twig",
    "TypeScript",
    "Typst",
    "Uiua",
    "Unison",
    "V",
    "Vala",
    "Verilog",
    "VHDL",
    "Vue.js",
    "WebAssembly Text Format",
    "Wgsl",
    "WIT",
    "XML",
    "YAML",
    "Yara",
    "Zig",
]
